version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - exhaustive
    - nilerr
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - unparam
      # G304 (file inclusion via variable) is not meaningful for this CLI tool
      # because all file paths are constructed from the managed data directory.
      - linters:
          - gosec
        text: "G304"
