version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - exhaustive
    - nilerr
    - unparam
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - unparam
