package cli

import (
	"context"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/valter-silva-au/ai-dev-brain/harnesses/claude"
	"github.com/valter-silva-au/ai-dev-brain/internal/core"
)

// wikiClassifier maps a task to its org + initiative for wiki namespacing, from
// the task's Initiative field (backlog) and that initiative's OrgID (registry).
// Either may be empty → the page lands ungrouped at the wiki root.
type wikiClassifier struct{}

func (wikiClassifier) Classify(taskID string) (string, string) {
	if App == nil || App.BacklogManager == nil {
		return "", ""
	}
	t, err := App.BacklogManager.GetTask(taskID)
	if err != nil || t == nil || t.Initiative == "" {
		return "", ""
	}
	org := ""
	if App.StageManager != nil {
		if in, err := App.StageManager.GetInitiative(t.Initiative); err == nil {
			org = in.OrgID
		}
	}
	return org, t.Initiative
}

// NewSyncCmd creates the sync command with all subcommands
func NewSyncCmd() *cobra.Command {
	syncCmd := &cobra.Command{
		Use:   "sync",
		Short: "Sync and regenerate context files",
		Long:  `Commands for regenerating context files for AI agents`,
	}

	// Add subcommands
	syncCmd.AddCommand(
		newSyncContextCmd(),
		newSyncTaskContextCmd(),
		newSyncReposCmd(),
		newSyncClaudeUserCmd(),
		newSyncWikiCmd(),
		newSyncIssuesCmd(), // WS-E: GitHub/GitLab issue sync (defined in sync_issues.go)
		newSyncAllCmd(),
		newSyncCloudCmd(), // WS-G: S3 archive plane. Sibling: WS-E adds `sync issues`.
	)

	return syncCmd
}

// newSyncWikiCmd creates the 'sync wiki' command — publishes each task's
// extracted knowledge (decisions, learnings, gotchas) as wiki markdown so
// the knowledge accumulated in tickets/<id>/knowledge/decisions.yaml flows
// OUT to a human-readable, cross-linkable knowledge base.
func newSyncWikiCmd() *cobra.Command {
	var outDir string

	cmd := &cobra.Command{
		Use:   "wiki [--out <dir>]",
		Short: "Publish extracted task knowledge as wiki markdown",
		Long: `Render one markdown page per task that has extracted knowledge.

Pages carry YAML frontmatter (title/created/updated/tags/source) and group
decisions, learnings, and gotchas under headings, so they drop straight into
a file-based wiki. With --out you can target an external wiki directory
outside the adb workspace (the in-tool knowledge stays authoritative).`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if App == nil {
				return fmt.Errorf("app not initialized")
			}
			if outDir == "" {
				outDir = App.BasePath + "/docs/wiki/knowledge"
			}

			publisher := core.NewWikiPublisher(App.BasePath)
			// Graph cross-links + org/initiative namespacing (issue #127).
			publisher.SetGraph(App.GraphManager)
			publisher.SetClassifier(wikiClassifier{})
			// Index the published corpus for semantic search when memory is
			// configured for the workspace (opt-in; same store search_knowledge reads).
			if store, configured, err := App.OpenMemoryStore(context.Background()); err == nil && configured {
				defer store.Close()
				publisher.SetIndexer(store)
			}

			fmt.Printf("Publishing task knowledge to %s...\n", outDir)
			res, err := publisher.PublishAll(outDir)
			if err != nil {
				return fmt.Errorf("failed to publish wiki: %w", err)
			}

			fmt.Printf("✓ %d page(s) + %d nav artifact(s) written, %d skipped (no knowledge), %d scanned",
				len(res.PagesWritten), len(res.IndexPages), len(res.Skipped), res.TasksScanned)
			if res.Indexed > 0 {
				fmt.Printf(", %d indexed for search", res.Indexed)
			}
			fmt.Println()
			for _, page := range res.PagesWritten {
				fmt.Printf("  + %s\n", page)
			}
			return nil
		},
	}

	cmd.Flags().StringVar(&outDir, "out", "", "Output directory (default: <workspace>/docs/wiki/knowledge)")

	return cmd
}

// newSyncContextCmd creates the 'sync context' command
func newSyncContextCmd() *cobra.Command {
	var rich bool
	var thin bool
	var force bool

	cmd := &cobra.Command{
		Use:   "context [--thin]",
		Short: "Regenerate the workspace agent instruction files",
		Long: `Regenerate the workspace's agent instruction files from backlog and task data.

The generated context is written to AGENTS.md — the agent-agnostic convention
(https://agents.md) — and a thin pointer file is maintained for each harness that
looks for its own filename instead. CLAUDE.md is the default pointer; set the
` + "`instruction_pointers`" + ` custom setting to change the list (comma-separated,
or "none" to write only AGENTS.md).

An instruction file that exists and was NOT generated by adb is left alone and
reported, so a hand-written CLAUDE.md is never silently replaced. Pass --force to
overwrite it anyway.

By default this uses the multi-section AIContextGenerator (overview, directory,
conventions, glossary, decisions, active tasks, critical decisions,
recent/captured sessions, stakeholders, "What's Changed") and maintains
.adb/context_state.yaml section-hashing for change detection.

With --thin, the legacy generator is used instead: it emits an overview plus a
raw dump of the whole backlog (archived tasks included). That was the historical
default, and it is LOSSY — running it over a file produced by the default drops
the Conventions and Stakeholders sections, which is why it is now opt-in.

--rich is accepted as a no-op alias for the default so existing scripts keep
working. --thin and --rich are mutually exclusive.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if App == nil {
				return fmt.Errorf("app not initialized")
			}

			if thin && rich {
				return fmt.Errorf("--thin and --rich are mutually exclusive")
			}

			// --rich is retained as a no-op so existing scripts keep working, but say
			// so. The notice goes to STDERR, not stdout: a caller redirecting this
			// command's output should not have a deprecation line land in it.
			if rich {
				fmt.Fprintln(cmd.ErrOrStderr(),
					"warning: --rich is deprecated and does nothing — the rich generator is now the default")
			}

			if thin {
				contextGen := core.NewContextGenerator(
					App.BasePath+"/backlog.yaml",
					App.BasePath+"/tickets",
					App.BasePath,
					App.TemplateManager,
				)

				fmt.Println("Regenerating instruction files (thin, legacy backlog dump)...")
				if err := contextGen.GenerateContext(); err != nil {
					return fmt.Errorf("failed to regenerate context: %w", err)
				}

				fmt.Println("✓ AGENTS.md + pointers regenerated (thin)")
				return nil
			}

			if App.AIContextGenerator == nil {
				return fmt.Errorf("AI context generator not initialized")
			}
			pointers := configuredInstructionPointers()
			fmt.Printf("Regenerating %s (multi-section)...\n", core.CanonicalInstructionFile)
			results, err := App.AIContextGenerator.GenerateInto(pointers, force)
			if err != nil {
				return fmt.Errorf("failed to regenerate context: %w", err)
			}
			reportInstructionResults(cmd, results)
			fmt.Println("✓ .adb/context_state.yaml updated")
			return nil
		},
	}

	cmd.Flags().BoolVar(&thin, "thin", false, "Use the legacy generator that dumps backlog.yaml (lossy)")
	cmd.Flags().BoolVar(&rich, "rich", false, "Deprecated: no-op alias for the default, kept so existing scripts keep working")
	cmd.Flags().BoolVar(&force, "force", false,
		"Overwrite an instruction file that adb did not generate (by default such a file is left alone)")

	return cmd
}

// configuredInstructionPointers resolves the per-harness pointer filenames from
// the layered config (repo > org > global), e.g. in ~/.taskconfig:
//
//	custom_settings:
//	  instruction_pointers: CLAUDE.md,CODEX.md      # or "none"
//
// Unset anywhere → core.DefaultInstructionPointers().
func configuredInstructionPointers() []string {
	if App == nil || App.MergedConfig == nil {
		return core.DefaultInstructionPointers()
	}
	v, _, ok := App.MergedConfig.SettingSource(core.InstructionPointersSetting)
	if !ok {
		return core.DefaultInstructionPointers()
	}
	return core.ParseInstructionPointers(v)
}

// reportInstructionResults prints one line per instruction file. A skipped file
// is the interesting case and goes to STDERR: adb declined to overwrite
// something the user wrote, and a silent skip would look identical to a
// successful sync while the agent kept reading stale context.
func reportInstructionResults(cmd *cobra.Command, results []core.InstructionFileResult) {
	for _, r := range results {
		switch r.Action {
		case core.InstructionWritten:
			fmt.Printf("  ✓ %s written\n", r.Name)
		case core.InstructionUnchanged:
			fmt.Printf("  = %s unchanged\n", r.Name)
		case core.InstructionSkipped:
			fmt.Fprintf(cmd.ErrOrStderr(), "  ⚠ %s skipped — %s\n", r.Name, r.Reason)
		}
	}
}

// newSyncTaskContextCmd creates the 'sync task-context' command
func newSyncTaskContextCmd() *cobra.Command {
	var hookMode bool

	cmd := &cobra.Command{
		Use:   "task-context <task-id>",
		Short: "Regenerate task-specific context",
		Long:  `Regenerate context.md for a specific task`,
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if App == nil {
				return fmt.Errorf("app not initialized")
			}

			taskID := args[0]

			// Refuse an id that adb has never heard of. Without this the generator
			// happily CREATES tickets/<whatever>/ for ANY string and prints a ✓,
			// so a typo silently fabricated a ticket directory that no backlog
			// entry owned — and the command reported success either way.
			//
			// "Heard of" is deliberately either/or, not backlog-only: a ticket
			// directory that exists on disk without a backlog entry is a real
			// state worth being able to regenerate context for. Only an id with
			// neither is a typo.
			if !taskIsKnown(taskID) {
				return fmt.Errorf(
					"unknown task %q — no backlog entry and no ticket directory "+
						"(list tasks with `adb task list`)",
					taskID,
				)
			}

			// Create context generator
			contextGen := core.NewContextGenerator(
				App.BasePath+"/backlog.yaml",
				App.BasePath+"/tickets",
				App.BasePath,
				App.TemplateManager,
			)

			fmt.Printf("Regenerating context for %s...\n", taskID)
			if err := contextGen.GenerateTaskContext(taskID, hookMode); err != nil {
				return fmt.Errorf("failed to regenerate task context: %w", err)
			}

			fmt.Printf("✓ Task context regenerated for %s\n", taskID)
			return nil
		},
	}

	cmd.Flags().BoolVar(&hookMode, "hook-mode", false, "Run in hook mode (append timestamp only)")

	return cmd
}

// newSyncReposCmd creates the 'sync repos' command
func newSyncReposCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "repos",
		Short: "Regenerate repository context",
		Long:  `Regenerate repository structure context`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if App == nil {
				return fmt.Errorf("app not initialized")
			}

			// Create context generator
			contextGen := core.NewContextGenerator(
				App.BasePath+"/backlog.yaml",
				App.BasePath+"/tickets",
				App.BasePath,
				App.TemplateManager,
			)

			fmt.Println("Regenerating repository context...")
			if err := contextGen.GenerateRepoContext(); err != nil {
				return fmt.Errorf("failed to regenerate repo context: %w", err)
			}

			fmt.Println("✓ Repository context regenerated")
			return nil
		},
	}

	return cmd
}

// newSyncClaudeUserCmd creates the 'sync claude-user' command
func newSyncClaudeUserCmd() *cobra.Command {
	var (
		dryRun bool
		mcp    bool
		force  bool
	)

	cmd := &cobra.Command{
		Use:   "claude-user",
		Short: "Regenerate Claude user context and install the Skills+Agents harness",
		Long: `Regenerate Claude-specific user context files, then install the embedded
Skills + Agents harness (the devils-advocate agent and the founder-playbook
skills) into your Claude Code config directory so Claude Code can load them.

Harness files install under <config>/agents and <config>/skills, where <config>
is $CLAUDE_CONFIG_DIR (if set) or ~/.claude. The install is idempotent: an
up-to-date file is left unchanged and a file you have edited is skipped rather
than clobbered (pass --force to overwrite). --dry-run previews without writing.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if App == nil {
				return fmt.Errorf("app not initialized")
			}

			// Create context generator
			contextGen := core.NewContextGenerator(
				App.BasePath+"/backlog.yaml",
				App.BasePath+"/tickets",
				App.BasePath,
				App.TemplateManager,
			)

			fmt.Println("Regenerating Claude user context...")
			if err := contextGen.GenerateClaudeUserContext(dryRun, mcp); err != nil {
				return fmt.Errorf("failed to regenerate Claude user context: %w", err)
			}
			if !dryRun {
				fmt.Println("✓ Claude user context regenerated")
			}

			return installClaudeHarness(cmd, dryRun, force)
		},
	}

	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Preview changes without writing")
	cmd.Flags().BoolVar(&mcp, "mcp", false, "Include MCP integration context")
	cmd.Flags().BoolVar(&force, "force", false, "Overwrite harness files that were edited (differ from the embedded copy)")

	return cmd
}

// installClaudeHarness installs the embedded Skills+Agents harness into the
// resolved Claude config dir and prints a per-file summary. The logic lives in
// core.InstallHarness; this handler only resolves the destination and renders.
func installClaudeHarness(cmd *cobra.Command, dryRun, force bool) error {
	claudeDir, err := resolveClaudeConfigDir()
	if err != nil {
		return err
	}

	res, err := core.InstallHarness(claude.FS, claudeDir, core.HarnessInstallOptions{DryRun: dryRun, Force: force})
	if err != nil {
		return fmt.Errorf("failed to install Claude harness: %w", err)
	}

	out := cmd.OutOrStdout()
	verb := "Installing"
	if dryRun {
		verb = "Would install"
	}
	fmt.Fprintf(out, "%s Claude harness into %s...\n", verb, claudeDir)
	for _, e := range res.Entries {
		note := ""
		if e.Action == core.HarnessSkipped {
			note = " (edited locally; pass --force to overwrite)"
		}
		// Show the path relative to the config dir for readability.
		rel, relErr := filepath.Rel(claudeDir, e.Dest)
		if relErr != nil {
			rel = e.Dest
		}
		fmt.Fprintf(out, "  %-9s %s%s\n", e.Action, filepath.ToSlash(rel), note)
	}
	fmt.Fprintf(out, "✓ Harness: %d installed, %d unchanged, %d skipped\n",
		res.Count(core.HarnessInstalled), res.Count(core.HarnessUnchanged), res.Count(core.HarnessSkipped))
	return nil
}

// resolveClaudeConfigDir returns the Claude Code config directory: $CLAUDE_CONFIG_DIR
// if set, else ~/.claude. This is the impure edge (env + home lookup); tests point
// CLAUDE_CONFIG_DIR at a temp dir to avoid touching the real config.
func resolveClaudeConfigDir() (string, error) {
	if d := os.Getenv("CLAUDE_CONFIG_DIR"); d != "" {
		return d, nil
	}
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolving home directory for the Claude config dir: %w", err)
	}
	return filepath.Join(home, ".claude"), nil
}

// newSyncAllCmd creates the 'sync all' command
func newSyncAllCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "all",
		Short: "Regenerate all context files",
		Long: `Regenerate all context files (agent instructions, repo context, user context).

AGENTS.md is produced by the same multi-section generator 'sync context' uses,
so 'sync all' can never flatten the rich instruction file into the legacy backlog dump.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if App == nil {
				return fmt.Errorf("app not initialized")
			}
			if App.AIContextGenerator == nil {
				return fmt.Errorf("AI context generator not initialized")
			}

			// Create context generator
			contextGen := core.NewContextGenerator(
				App.BasePath+"/backlog.yaml",
				App.BasePath+"/tickets",
				App.BasePath,
				App.TemplateManager,
			)

			fmt.Println("Regenerating all context files...")

			// Deliberately NOT contextGen.GenerateAll(): its GenerateContext step is
			// the legacy backlog dump, which would undo the rich instruction file
			// that 'sync context' writes by default. Generate the three artifacts
			// individually so AGENTS.md comes from the multi-section generator — and
			// honour the same configured pointer set, or 'sync all' would quietly
			// write a different set of files than 'sync context'.
			results, err := App.AIContextGenerator.GenerateInto(
				configuredInstructionPointers(), false,
			)
			if err != nil {
				return fmt.Errorf("failed to regenerate agent instructions: %w", err)
			}
			reportInstructionResults(cmd, results)
			if err := contextGen.GenerateRepoContext(); err != nil {
				return fmt.Errorf("failed to generate repo context: %w", err)
			}
			if err := contextGen.GenerateClaudeUserContext(false, false); err != nil {
				return fmt.Errorf("failed to generate Claude user context: %w", err)
			}

			fmt.Println("✓ All context files regenerated")
			return nil
		},
	}

	return cmd
}

// taskIsKnown reports whether adb has any record of taskID — a backlog entry or
// a ticket directory on disk. It is the guard that stops `adb context task`
// from fabricating a ticket tree for a mistyped id and reporting success.
//
// Resolution goes through core.ResolveTicketDir rather than a bare path join, so
// a ticket nested under the correlation layout (tickets/<platform>/<org>/<repo>/…)
// counts as known — a flat-path-only check would reject every repo-backed ticket.
func taskIsKnown(taskID string) bool {
	if taskID == "" || App == nil {
		return false
	}
	if App.BacklogManager != nil {
		if task, err := App.BacklogManager.GetTask(taskID); err == nil && task != nil {
			return true
		}
	}
	dir, err := core.ResolveTicketDir(filepath.Join(App.BasePath, "tickets"), taskID)
	if err == nil && dir != "" {
		if info, statErr := os.Stat(dir); statErr == nil && info.IsDir() {
			return true
		}
	}
	return false
}
